# fly.toml app configuration file generated for gareconnect-demo-cool-headland-7865 on 2026-07-10T19:15:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gareconnect-demo-cool-headland-7865'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
